---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
# Секция "Service" определяет сервис, который обеспечивает доступ к приложению Nginx:
#    apiVersion: v1 - используется API-версия v1.
#    kind: Service - определяет, что это объект типа "Service".
#    metadata - содержит метаданные сервиса.
#    name: nginx - задает имя сервиса "nginx".
#    spec - определяет спецификацию сервиса.
#    type: LoadBalancer - указывает тип сервиса "LoadBalancer", что позволяет использовать балансировщик нагрузки для распределения трафика.
#    selector - задает селектор, который связывает сервис с подами, помеченными меткой "app: nginx".
#    ports - определяет порты сервиса, в данном случае пробрасывается порт 80 (хостовой порт) на целевой порт 80 внутри подов.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: dos18/diploma:latest
# Секция "Deployment" определяет развертывание (Deployment) для приложения Nginx:
#    apiVersion: apps/v1 - используется API-версия apps/v1.
#    kind: Deployment - определяет, что это объект типа "Deployment".
#    metadata - содержит метаданные развертывания.
#    name: nginx - задает имя развертывания "nginx".
#    labels - определяет метки (labels) для развертывания, в данном случае метка "app: nginx".
#    spec - определяет спецификацию развертывания.
#    replicas: 2 - указывает желаемое количество реплик (подов) - 2.
#    selector - задает селектор, который связывает развертывание с подами, помеченными меткой "app: nginx".
#    template - определяет шаблон конфигурации пода.
#    metadata - содержит метаданные шаблона пода.
#    labels - определяет метки (labels) для пода, в данном случае метка "app: nginx".
#    spec - определяет спецификацию пода.
#    containers - определяет контейнеры, которые будут запущены в поде.
#    name: nginx - задает имя контейнера "nginx".
#    image: dos18/diploma:latest - указывает на использование образа dos18/diploma:latest для контейнера.

