name: Pre Derployment checks

on:
  push:
    branches:
    - main
    - dev

jobs:
  PreDerploymentChecks:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Git code chekout
      uses: actions/checkout@v4
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Run Lint Terraform
      uses: actionshub/terraform-lint@main  

    - name: Run Terraform Init
      run: |
        mv google google.json
        pwd
        export GOOGLE_APPLICATION_CREDENTIALS = /google.json
        cd terraform
        terraform init
    
    - name: Run Terraform Plan
      run: terraform plan
