name: Pre Derployment checks

on:
  push:
    branches:
    - main
    - dev

jobs:
  PreDerploymentChecks:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Git code chekout
      uses: actions/checkout@main
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Run Lint Terraform
      uses: actionshub/terraform-lint@main
       
    - name: Run Terraform Init
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        cd terraform
        export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
        terraform init
    
    - name: Run Terraform Plan
      run: terraform plan
