name: Pre Deployment checks

on:
  push:
    branches:
      - main
      - dev

jobs:
  PreDeploymentChecks:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
   
    steps:
    - name: Git code checkout
      uses: actions/checkout@v4
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Run Lint Terraform
      uses: actionshub/terraform-lint@main  

#    - name: Run Terraform Init
#      run: |
#        cd terraform
#        terraform init
#      env:
#        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

#    - name: Run Terraform Plan
#      run: |
#        cd terraform
#        terraform plan -input=false
#      env:
#        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

#    - name: Terraform Apply
#      run: |
#        cd terraform
#        terraform apply -auto-approve -input=false
#      env:
#        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Build local the Docker image
      run: |
        cd Docker
        docker build -t nginx .
        docker run --name nginx -p 80:8080 nginx
        docker start nginx
        curl 127.0.0.1
