name: Pre Derployment checks

on:
  push:
    branches:
    - main
    - dev

jobs:
  PreDerploymentChecks:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Git code chekout
      uses: actions/checkout@v4
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        terraform_wrapper: false

    - name: Run Lint Terraform
      uses: actionshub/terraform-lint@main  

    - name: Run Terraform Init
      run: |
        cd terraform
        export GOOGLE_APPLICATION_CREDENTIALS = @cli_config_credentials_token
        terraform init
    
    - name: Run Terraform Plan
      run: terraform plan
